language: go

go:
  - "1.9"

before_install:
  - brew install mingw-w64

script:
  - GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags -H=windowsgui -o Windows-ProxyChecker.exe
  #- GOOS=linux CGO_ENABLED=1 go build -o Linux-ProxyChecker
  - go build -o macOS-ProxyChecker

deploy:
  provider: releases
  api_key: $TOKEN
  file:
  - "Windows-ProxyChecker.exe"
  - "macOS-ProxyChecker"
  skip_cleanup: true
  on:
    tags: false

os: osx