language: go

go:
  - "1.10"

addons:
  apt:
    packages:
      - libgtk-3-dev
      - mingw-w64
      - cmake

script:
  - go get github.com/andlabs/ui
  - wget https://github.com/andlabs/libui/releases/tag/alpha3.5
  - tar -zxvf alpha3.5.tgz
  - cd alpha3.5/src
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF ..
  - make
  - cp out/libui.a ${GOPATH}/src/github.com/andlabs/ui/libui_linux_amd64.a
  - cd ${GOPATH}/src/github.com/andlabs/ui/
  - go build
  - cd $HOME/gopath/src/github.com/trigun117/ProxyChecker
  - GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags -H=windowsgui -o ProxyChecker.exe
  - go build -o ProxyChecker

deploy:
  provider: releases
  api_key: $TOKEN
  file:
  - "ProxyChecker.exe"
  - "ProxyChecker"
  skip_cleanup: true
  on:
    tags: false
branches:
  only:
    - master