language: go
go: 
  - "1.9"

matrix:
  include:

    - os: osx
      before_install:
        - brew install mingw-w64
      script:
        - chmod +x test.sh
        - ./test.sh
        - GOOS=windows CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags -H=windowsgui -o Windows-ProxyChecker.exe
        - go build -o macOS-ProxyChecker

    - os: linux
      before_install:
        - chmod +x test.sh
        - ./test.sh
        - sudo apt-get update
        - sudo apt-get install libgtk-3-dev -y
      script:
        - go build -o Linux-ProxyChecker

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: $TOKEN
  file:
  - "Windows-ProxyChecker.exe"
  - "Linux-ProxyChecker"
  - "macOS-ProxyChecker"
  skip_cleanup: true
  on:
    tags: false

branches:
  only:
    - master